[build]
  command = "npm install next && npm run build"
  publish = ".next"
  base = "/app"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.deploy-preview]
  command = "npm run build-preview"